#!/bin/bash
# Comandos rápidos para configurar na EC2

echo "=================================================="
echo "🚀 SETUP RÁPIDO - Alertas do Slack"
echo "=================================================="
echo ""
echo "Execute os comandos abaixo na EC2:"
echo ""
echo "# 1. Atualizar código"
echo "cd /home/ubuntu/statuspage"
echo "git pull"
echo ""
echo "# 2. Instalar dependência"
echo "pip3 install python-dotenv"
echo ""
echo "# 3. Criar configuração"
echo "cp monitor-config.env.example monitor-config.env"
echo "nano monitor-config.env"
echo ""
echo "# Preencha com suas credenciais reais:"
echo "#   SLACK_WEBHOOK=https://hooks.slack.com/services/..."
echo "#   DB_USER=seu_usuario"
echo "#   DB_PASSWORD=sua_senha_real"
echo ""
echo "# 4. Proteger arquivo"
echo "chmod 600 monitor-config.env"
echo ""
echo "# 5. Validar"
echo "python3 validate-monitor-config.py"
echo ""
echo "# 6. Testar Slack"
echo "python3 test-slack.py"
echo ""
echo "# 7. Testar monitor"
echo "python3 monitor.py"
echo ""
echo "=================================================="
echo "✅ Pronto! Alertas devem estar funcionando"
echo "=================================================="
